# Generated by Django 4.2.15 on 2024-12-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_adv_article_adv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adv',
            name='count_of_sale',
        ),
    ]
