# Generated by Django 4.2.15 on 2024-12-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_adv_count_of_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='count_of_sale',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
